# Numpy Matrix
Numpy 로 Matrix를 생성하는 방법들을 알아봅니다.

## Import
보통 np 로 줄여서 많이 쓰입니다.

In [1]:
import numpy as np

## 직접 matrix 를 생성하는 방법

In [2]:
x = np.matrix('1 2; 3 4')
print (x)

[[1 2]
 [3 4]]


## reshape 를 통해 생성하는 방법

In [3]:
np.arange(25).reshape((5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [4]:
np.array(range(25)).reshape((-1, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [5]:
a=np.ones(12)
a=a.reshape(-1,3)
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Array 를 Matrix 형태로 생성하기

In [6]:
np.ndarray((5,5))

array([[4.63803223e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000]])

## 값에 접근하는 방법<BR>
- a 라는 matrix 를 생성한다.

In [7]:
a=np.array([[1, 2],[3, 4]])
a

array([[1, 2],
       [3, 4]])

- a[행][렬] 의 형식으로 접근한다.

In [8]:
a[1][0]

3

# Matrix Examples
2차원으로 3차원 만들기
- 일괄 생성시 상위 차원 1 추가하기
- 숫자 입력시 각 괄호 입력

In [9]:
i1 = np.ones((1,2,2))
i1

array([[[1., 1.],
        [1., 1.]]])

In [10]:
i2 = np.array([[[1,2,],[3,4]]])
i2.shape

(1, 2, 2)

In [11]:
a = np.vstack( (i1, i2, i1))
print (f"{a.shape}\n\n{a}")

(3, 2, 2)

[[[1. 1.]
  [1. 1.]]

 [[1. 2.]
  [3. 4.]]

 [[1. 1.]
  [1. 1.]]]
