# Numpy Intro
Numpy 는 다차원 배열을 쉽게 처리하고 효율적으로 사용할 수 있도록 지원하는 파이썬의 패키지로 데이터 구조 외에도 수치 계산을 위해 효율적으로 구현된 기능을 제공합니다.<BR>
데이터 분석을 할 때, [Pandas](https://pandas.pydata.org/) 와 함께 자주 사용하는 도구로 등장합니다.

## Install
pip 를 이용해 인스톨 가능합니다. Colab 에선 이미 설치되어 지원하기 때문에 생략해도 됩니다.

In [1]:
# !pip install numpy

## Basic Usage

### Import
보통 np 로 줄여서 많이 쓰입니다.

In [2]:
import numpy as np

version 확인

In [3]:
np.__version__

'1.19.5'

### data 형 바꿔보기

np array 생성

In [4]:
data = [[1,2],[3,4]]
arr = np.array(data)
arr.shape

(2, 2)

차원수 확인

In [5]:
arr.ndim

2

reshape 로 바꿔주기

In [6]:
arr2 = arr.reshape((-1))
arr2.shape

(4,)

In [7]:
arr2.ndim

1

### 행렬 만들기

데이터가 비어 있는 행렬 만들기

In [8]:
np.empty((3,3))

array([[4.64697670e-310, 3.60739284e-313, 1.38338381e-322],
       [4.64697670e-310, 0.00000000e+000, 0.00000000e+000],
       [4.94065646e-323, 0.00000000e+000, 0.00000000e+000]])

1 로 채워진 행렬 만들기

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

0 으로 채워진 행렬 만들기

In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Arange 함수
반열린구간 [start, stop) 에서 step 의 크기만큼 일정하게 떨어져 있는 숫자들을 array 형태로 반환해 주는 함수다.

출처: https://codepractice.tistory.com/88 [코딩 연습]

stop 매개변수의 값만 전달하면 0을 시작으로 1 간격으로 떨어진 수들을 반환한다.

In [11]:
np.arange(5)

array([0, 1, 2, 3, 4])


start 와 stop 이 주어진 경우로 반열린구간 [start, stop) 에서 start 를 시작으로 1 간격으로 떨어진 수들을 반환한다.

In [12]:
np.arange(3,7)


array([3, 4, 5, 6])

start, stop, step 이 모두 주어지면 start 를 시작으로  stop 이 되기 전까지의 step 간격으로 떨어진 수들을 반환한다.   

In [13]:
np.arange(3,9,2)

array([3, 5, 7])

## Matrix Basic

### 직접 matrix 를 생성하는 방법

In [14]:
x = np.matrix('1 2; 3 4')
print (x)

[[1 2]
 [3 4]]


### reshape 를 통해 생성하는 방법

In [15]:
np.arange(25).reshape((5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
np.array(range(25)).reshape((-1, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
a=np.ones(12)
a=a.reshape(-1,3)
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Array 를 Matrix 형태로 생성하기

In [18]:
np.ndarray((5,5))

array([[4.64697552e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000]])

### 값에 접근하는 방법<BR>
- a 라는 matrix 를 생성한다.

In [19]:
a=np.array([[1, 2],[3, 4]])
a

array([[1, 2],
       [3, 4]])

- a[행][렬] 의 형식으로 접근한다.

In [20]:
a[1][0]

3

## Matrix Examples
2차원으로 3차원 만들기
- 일괄 생성시 상위 차원 1 추가하기
- 숫자 입력시 각 괄호 입력

In [21]:
i1 = np.ones((1,2,2))
i1

array([[[1., 1.],
        [1., 1.]]])

In [22]:
i2 = np.array([[[1,2,],[3,4]]])
i2.shape

(1, 2, 2)

In [23]:
a = np.vstack( (i1, i2, i1))
print (f"{a.shape}\n\n{a}")

(3, 2, 2)

[[[1. 1.]
  [1. 1.]]

 [[1. 2.]
  [3. 4.]]

 [[1. 1.]
  [1. 1.]]]


## ETC

요리해볼 Array 

In [24]:
arr=np.array([[1,2,],[3,-4]])


### abs 함수
- 절대값을 리턴.

In [25]:
np.abs(arr)

array([[1, 2],
       [3, 4]])

### sqrt 함수
- 제곱근(루트)을 계산함.

In [26]:
np.sqrt(arr)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([[1.        , 1.41421356],
       [1.73205081,        nan]])

### 행렬곱하기
- * 를 통해 곱하기 가능

In [27]:
arr*arr

array([[ 1,  4],
       [ 9, 16]])

### dot 함수
두 1차원 어레이 a, b의 곱에 대해, np.dot(a, b)는 두 벡터의 내적 (Dot product)을 반환합니다.<br>
(0차원, 2차원은 * 를 권장합니다.)

In [28]:
np.dot(arr[0],arr[1])

-5

## inv Example

y=2x+1, y=-x+4

In [29]:
a = np.array([[1, -2], [1, 1]])
b = np.array([[1],[4]])
np.dot(np.linalg.inv(a),b)

array([[3.],
       [1.]])