# Numpy Intro
Numpy 는 다차원 배열을 쉽게 처리하고 효율적으로 사용할 수 있도록 지원하는 파이썬의 패키지로 데이터 구조 외에도 수치 계산을 위해 효율적으로 구현된 기능을 제공합니다.<BR>
데이터 분석을 할 때, [Pandas](https://pandas.pydata.org/) 와 함께 자주 사용하는 도구로 등장합니다.

## Install
pip 를 이용해 인스톨 가능합니다. Colab 에선 이미 설치되어 지원하기 때문에 생략해도 됩니다.

In [ ]:
# !pip install numpy

## Basic Usage

### Import
보통 np 로 줄여서 많이 쓰입니다.

In [1]:
import numpy as np

version 확인

In [2]:
np.__version__

'1.19.5'

### data 형 바꿔보기

In [5]:
data = [[1,2],[3,4]]
arr = np.array(data)
arr.shape

(2, 2)

In [6]:
arr.ndim

2

### 데이터가 비어 있는 행렬 만들기

In [7]:
np.empty((3,3))

array([[4.65737467e-310, 0.00000000e+000, 0.00000000e+000],
       [4.65735636e-310, 0.00000000e+000, 4.24399159e-314],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

### 1 로 채워진 행렬 만들기

In [8]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 0 으로 채워진 행렬 만들기

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])