# Numpy Fuction
Numpy 에서 Data를 다룰 때 쓰이는 Fuction 들을 알아봅니다.

## Import 

In [1]:
import numpy as np

## Arange 함수
반열린구간 [start, stop) 에서 step 의 크기만큼 일정하게 떨어져 있는 숫자들을 array 형태로 반환해 주는 함수다.

출처: https://codepractice.tistory.com/88 [코딩 연습]

stop 매개변수의 값만 전달하면 0을 시작으로 1 간격으로 떨어진 수들을 반환한다.

In [2]:
np.arange(5)

array([0, 1, 2, 3, 4])

start 와 stop 이 주어진 경우로 반열린구간 [start, stop) 에서 start 를 시작으로 1 간격으로 떨어진 수들을 반환한다.

In [3]:
np.arange(3,7)

array([3, 4, 5, 6])

start, stop, step 이 모두 주어지면 start 를 시작으로  stop 이 되기 전까지의 step 간격으로 떨어진 수들을 반환한다.

In [4]:
np.arange(3,9,2)

array([3, 5, 7])

## abs 함수
- 절대값을 리턴.

In [5]:
arr=np.array([[1,2,],[3,-4]])
np.abs(arr)

array([[1, 2],
       [3, 4]])

## sqrt 함수
- 제곱근(루트)을 계산함.

In [6]:
np.sqrt(arr)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([[1.        , 1.41421356],
       [1.73205081,        nan]])

## 행렬곱하기
- * 를 통해 곱하기 가능

In [7]:
arr*arr

array([[ 1,  4],
       [ 9, 16]])

## dot 함수
두 1차원 어레이 a, b의 곱에 대해, np.dot(a, b)는 두 벡터의 내적 (Dot product)을 반환합니다.<br>
(0차원, 2차원은 * 를 권장합니다.)

In [8]:
np.dot(arr[0],arr[1])

-5